name: Deployment Excersise
on: [push, workflow_dispatch]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: This is CI part
        run: echo "Continueos integration is done"
  CD:
    runs-on: ubuntu-latest
    steps:
      - name: This is CD part
        run: echo "Deploying !!!"
